const SCHOOL_PLAN = [
  {
    "id": "2-1-1",
    "day": 2,
    "number": 1,
    "start": "08:00",
    "end": "08:45",
    "subject": "projektowanie i administrowanie bazami danych",
    "kind": "teoria",
    "teacher": "Po",
    "room": "23",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-1-2",
    "day": 2,
    "number": 1,
    "start": "08:00",
    "end": "08:45",
    "subject": "projektowanie i administrowanie bazami danych",
    "kind": "teoria",
    "teacher": "Po",
    "room": "23",
    "group": 2,
    "optional": false
  },
  {
    "id": "4-1-1",
    "day": 4,
    "number": 1,
    "start": "08:00",
    "end": "08:45",
    "subject": "Geografia",
    "kind": "",
    "teacher": "LM",
    "room": "54",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-1-2",
    "day": 4,
    "number": 1,
    "start": "08:00",
    "end": "08:45",
    "subject": "Geografia",
    "kind": "",
    "teacher": "LM",
    "room": "54",
    "group": 2,
    "optional": false
  },
  {
    "id": "5-1-1",
    "day": 5,
    "number": 1,
    "start": "08:00",
    "end": "08:45",
    "subject": "projektowanie i tworzenie stron internetowych",
    "kind": "praktyka",
    "teacher": "KC",
    "room": "18",
    "group": 1,
    "optional": false
  },
  {
    "id": "5-1-2",
    "day": 5,
    "number": 1,
    "start": "08:00",
    "end": "08:45",
    "subject": "Informatyka",
    "kind": "",
    "teacher": "Kh",
    "room": "69",
    "group": 2,
    "optional": false
  },
  {
    "id": "1-2-1",
    "day": 1,
    "number": 2,
    "start": "08:50",
    "end": "09:35",
    "subject": "Wychowanie fizyczne",
    "kind": "",
    "teacher": "Bu",
    "room": "s3",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-2-1",
    "day": 2,
    "number": 2,
    "start": "08:50",
    "end": "09:35",
    "subject": "projektowanie i administrowanie bazami danych",
    "kind": "teoria",
    "teacher": "Po",
    "room": "23",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-2-2",
    "day": 2,
    "number": 2,
    "start": "08:50",
    "end": "09:35",
    "subject": "projektowanie i administrowanie bazami danych",
    "kind": "teoria",
    "teacher": "Po",
    "room": "23",
    "group": 2,
    "optional": false
  },
  {
    "id": "3-2-1",
    "day": 3,
    "number": 2,
    "start": "08:50",
    "end": "09:35",
    "subject": "Język angielski",
    "kind": "",
    "teacher": "CI",
    "room": "52",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-2-1",
    "day": 4,
    "number": 2,
    "start": "08:50",
    "end": "09:35",
    "subject": "Wychowanie fizyczne",
    "kind": "",
    "teacher": "Bu",
    "room": "s2",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-2-2",
    "day": 4,
    "number": 2,
    "start": "08:50",
    "end": "09:35",
    "subject": "Wychowanie fizyczne",
    "kind": "",
    "teacher": "ŁC",
    "room": "s4",
    "group": 2,
    "optional": false
  },
  {
    "id": "5-2-1",
    "day": 5,
    "number": 2,
    "start": "08:50",
    "end": "09:35",
    "subject": "projektowanie i tworzenie stron internetowych",
    "kind": "praktyka",
    "teacher": "KC",
    "room": "18",
    "group": 1,
    "optional": false
  },
  {
    "id": "5-2-2",
    "day": 5,
    "number": 2,
    "start": "08:50",
    "end": "09:35",
    "subject": "Informatyka",
    "kind": "",
    "teacher": "Kh",
    "room": "69",
    "group": 2,
    "optional": false
  },
  {
    "id": "1-3-1",
    "day": 1,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "Wychowanie fizyczne",
    "kind": "",
    "teacher": "Bu",
    "room": "s3",
    "group": 1,
    "optional": false
  },
  {
    "id": "1-3-2",
    "day": 1,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "Język niemiecki",
    "kind": "",
    "teacher": "Sz",
    "room": "42a",
    "group": 2,
    "optional": false
  },
  {
    "id": "2-3-1",
    "day": 2,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "projektowanie i administrowanie bazami danych",
    "kind": "praktyka",
    "teacher": "Po",
    "room": "18",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-3-2",
    "day": 2,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "Informatyka rozszerzona",
    "kind": "",
    "teacher": "Kh",
    "room": "69",
    "group": 2,
    "optional": false
  },
  {
    "id": "3-3-1",
    "day": 3,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "Informatyka",
    "kind": "",
    "teacher": "Kh",
    "room": "69",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-3-1",
    "day": 4,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "Informatyka rozszerzona",
    "kind": "",
    "teacher": "Kh",
    "room": "69",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-3-2",
    "day": 4,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "projektowanie i tworzenie stron internetowych",
    "kind": "praktyka",
    "teacher": "KC",
    "room": "18",
    "group": 2,
    "optional": false
  },
  {
    "id": "5-3-1",
    "day": 5,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "Historia",
    "kind": "",
    "teacher": "JO",
    "room": "68",
    "group": 1,
    "optional": false
  },
  {
    "id": "5-3-2",
    "day": 5,
    "number": 3,
    "start": "09:45",
    "end": "10:30",
    "subject": "Historia",
    "kind": "",
    "teacher": "JO",
    "room": "68",
    "group": 2,
    "optional": false
  },
  {
    "id": "1-4-1",
    "day": 1,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "Język polski",
    "kind": "",
    "teacher": "MS",
    "room": "80",
    "group": 1,
    "optional": false
  },
  {
    "id": "1-4-2",
    "day": 1,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "Język polski",
    "kind": "",
    "teacher": "MS",
    "room": "80",
    "group": 2,
    "optional": false
  },
  {
    "id": "2-4-1",
    "day": 2,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "projektowanie i administrowanie bazami danych",
    "kind": "praktyka",
    "teacher": "Po",
    "room": "18",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-4-2",
    "day": 2,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "Wychowanie fizyczne",
    "kind": "",
    "teacher": "ŁC",
    "room": "s2",
    "group": 2,
    "optional": false
  },
  {
    "id": "3-4-1",
    "day": 3,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "Informatyka",
    "kind": "",
    "teacher": "Kh",
    "room": "69",
    "group": 1,
    "optional": false
  },
  {
    "id": "3-4-2",
    "day": 3,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "Język niemiecki",
    "kind": "",
    "teacher": "Sz",
    "room": "42a",
    "group": 2,
    "optional": false
  },
  {
    "id": "4-4-1",
    "day": 4,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "Język niemiecki",
    "kind": "",
    "teacher": "GO",
    "room": "42b",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-4-2",
    "day": 4,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "projektowanie i tworzenie stron internetowych",
    "kind": "praktyka",
    "teacher": "KC",
    "room": "18",
    "group": 2,
    "optional": false
  },
  {
    "id": "5-4-1",
    "day": 5,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "Matematyka",
    "kind": "",
    "teacher": "HŻ",
    "room": "82",
    "group": 1,
    "optional": false
  },
  {
    "id": "5-4-2",
    "day": 5,
    "number": 4,
    "start": "10:35",
    "end": "11:20",
    "subject": "Matematyka",
    "kind": "",
    "teacher": "HŻ",
    "room": "82",
    "group": 2,
    "optional": false
  },
  {
    "id": "1-5-1",
    "day": 1,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "Język polski",
    "kind": "",
    "teacher": "MS",
    "room": "80",
    "group": 1,
    "optional": false
  },
  {
    "id": "1-5-2",
    "day": 1,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "Język polski",
    "kind": "",
    "teacher": "MS",
    "room": "80",
    "group": 2,
    "optional": false
  },
  {
    "id": "2-5-1",
    "day": 2,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "Język angielski",
    "kind": "",
    "teacher": "CI",
    "room": "52",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-5-2",
    "day": 2,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "Wychowanie fizyczne",
    "kind": "",
    "teacher": "ŁC",
    "room": "s2",
    "group": 2,
    "optional": false
  },
  {
    "id": "3-5-1",
    "day": 3,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "Fizyka",
    "kind": "",
    "teacher": "WA",
    "room": "71",
    "group": 1,
    "optional": false
  },
  {
    "id": "3-5-2",
    "day": 3,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "Fizyka",
    "kind": "",
    "teacher": "WA",
    "room": "71",
    "group": 2,
    "optional": false
  },
  {
    "id": "4-5-1",
    "day": 4,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "Matematyka",
    "kind": "",
    "teacher": "HŻ",
    "room": "82",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-5-2",
    "day": 4,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "Matematyka",
    "kind": "",
    "teacher": "HŻ",
    "room": "82",
    "group": 2,
    "optional": false
  },
  {
    "id": "5-5-1",
    "day": 5,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "projektowanie i tworzenie stron internetowych",
    "kind": "teoria",
    "teacher": "KC",
    "room": "54",
    "group": 1,
    "optional": false
  },
  {
    "id": "5-5-2",
    "day": 5,
    "number": 5,
    "start": "11:30",
    "end": "12:15",
    "subject": "projektowanie i tworzenie stron internetowych",
    "kind": "teoria",
    "teacher": "KC",
    "room": "54",
    "group": 2,
    "optional": false
  },
  {
    "id": "1-6-1",
    "day": 1,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "Bezpieczeństwo i higiena pracy",
    "kind": "",
    "teacher": "ŁC",
    "room": "68",
    "group": 1,
    "optional": false
  },
  {
    "id": "1-6-2",
    "day": 1,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "Bezpieczeństwo i higiena pracy",
    "kind": "",
    "teacher": "ŁC",
    "room": "68",
    "group": 2,
    "optional": false
  },
  {
    "id": "2-6-1",
    "day": 2,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "Biologia",
    "kind": "",
    "teacher": "MŁ",
    "room": "64",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-6-2",
    "day": 2,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "Biologia",
    "kind": "",
    "teacher": "MŁ",
    "room": "64",
    "group": 2,
    "optional": false
  },
  {
    "id": "3-6-1",
    "day": 3,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "język angielski zawodowy",
    "kind": "teoria",
    "teacher": "CI",
    "room": "48",
    "group": 1,
    "optional": false
  },
  {
    "id": "3-6-2",
    "day": 3,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "język angielski zawodowy",
    "kind": "teoria",
    "teacher": "CI",
    "room": "48",
    "group": 2,
    "optional": false
  },
  {
    "id": "4-6-1",
    "day": 4,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "Język polski",
    "kind": "",
    "teacher": "MS",
    "room": "80",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-6-2",
    "day": 4,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "Język polski",
    "kind": "",
    "teacher": "MS",
    "room": "80",
    "group": 2,
    "optional": false
  },
  {
    "id": "5-6-1",
    "day": 5,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "projektowanie i tworzenie stron internetowych",
    "kind": "teoria",
    "teacher": "KC",
    "room": "54",
    "group": 1,
    "optional": false
  },
  {
    "id": "5-6-2",
    "day": 5,
    "number": 6,
    "start": "12:20",
    "end": "13:05",
    "subject": "projektowanie i tworzenie stron internetowych",
    "kind": "teoria",
    "teacher": "KC",
    "room": "54",
    "group": 2,
    "optional": false
  },
  {
    "id": "1-7-1",
    "day": 1,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "Matematyka",
    "kind": "",
    "teacher": "HŻ",
    "room": "82",
    "group": 1,
    "optional": false
  },
  {
    "id": "1-7-2",
    "day": 1,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "Matematyka",
    "kind": "",
    "teacher": "HŻ",
    "room": "82",
    "group": 2,
    "optional": false
  },
  {
    "id": "2-7-1",
    "day": 2,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "Język niemiecki",
    "kind": "",
    "teacher": "GO",
    "room": "42b",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-7-2",
    "day": 2,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "Język angielski",
    "kind": "",
    "teacher": "SR",
    "room": "6i",
    "group": 2,
    "optional": false
  },
  {
    "id": "3-7-1",
    "day": 3,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "Biznes i zarządzanie",
    "kind": "",
    "teacher": "SG",
    "room": "68",
    "group": 1,
    "optional": false
  },
  {
    "id": "3-7-2",
    "day": 3,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "Biznes i zarządzanie",
    "kind": "",
    "teacher": "SG",
    "room": "68",
    "group": 2,
    "optional": false
  },
  {
    "id": "4-7-1",
    "day": 4,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "podstawy informatyki",
    "kind": "teoria",
    "teacher": "BO",
    "room": "54",
    "group": 1,
    "optional": false
  },
  {
    "id": "4-7-2",
    "day": 4,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "podstawy informatyki",
    "kind": "teoria",
    "teacher": "BO",
    "room": "54",
    "group": 2,
    "optional": false
  },
  {
    "id": "5-7-2",
    "day": 5,
    "number": 7,
    "start": "13:25",
    "end": "14:10",
    "subject": "Język angielski",
    "kind": "",
    "teacher": "SR",
    "room": "6i",
    "group": 2,
    "optional": false
  },
  {
    "id": "1-8-1",
    "day": 1,
    "number": 8,
    "start": "14:30",
    "end": "15:15",
    "subject": "Edukacja dla bezpieczeństwa",
    "kind": "",
    "teacher": "TA",
    "room": "77",
    "group": 1,
    "optional": false
  },
  {
    "id": "1-8-2",
    "day": 1,
    "number": 8,
    "start": "14:30",
    "end": "15:15",
    "subject": "Edukacja dla bezpieczeństwa",
    "kind": "",
    "teacher": "TA",
    "room": "77",
    "group": 2,
    "optional": false
  },
  {
    "id": "2-8-1",
    "day": 2,
    "number": 8,
    "start": "14:30",
    "end": "15:15",
    "subject": "Zajęcia z wychowawcą",
    "kind": "",
    "teacher": "Kh",
    "room": "20",
    "group": 1,
    "optional": false
  },
  {
    "id": "2-8-2",
    "day": 2,
    "number": 8,
    "start": "14:30",
    "end": "15:15",
    "subject": "Zajęcia z wychowawcą",
    "kind": "",
    "teacher": "Kh",
    "room": "20",
    "group": 2,
    "optional": false
  },
  {
    "id": "3-8-1",
    "day": 3,
    "number": 8,
    "start": "14:30",
    "end": "15:15",
    "subject": "Chemia",
    "kind": "",
    "teacher": "Sa",
    "room": "64",
    "group": 1,
    "optional": false
  },
  {
    "id": "3-8-2",
    "day": 3,
    "number": 8,
    "start": "14:30",
    "end": "15:15",
    "subject": "Chemia",
    "kind": "",
    "teacher": "Sa",
    "room": "64",
    "group": 2,
    "optional": false
  },
  {
    "id": "1-9-1",
    "day": 1,
    "number": 9,
    "start": "15:25",
    "end": "16:10",
    "subject": "Religia",
    "kind": "",
    "teacher": "RK",
    "room": "76",
    "group": 1,
    "optional": true
  },
  {
    "id": "3-9-2",
    "day": 3,
    "number": 9,
    "start": "15:25",
    "end": "16:10",
    "subject": "projektowanie i administrowanie bazami danych",
    "kind": "praktyka",
    "teacher": "Po",
    "room": "18",
    "group": 2,
    "optional": false
  },
  {
    "id": "3-10-2",
    "day": 3,
    "number": 10,
    "start": "16:15",
    "end": "17:00",
    "subject": "projektowanie i administrowanie bazami danych",
    "kind": "praktyka",
    "teacher": "Po",
    "room": "18",
    "group": 2,
    "optional": false
  }
];
